# -*- coding: utf-8 -*-
"""plasticity_fenicsx.ipynb

# https://www.youtube.com/watch?v=MQE2an9JV0M

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PfGO-cJutLm6qct7SH_ccSbht_LhfZbJ
"""

# install required packages
# %pip install -q condacolab
# import condacolab
# condacolab.install()

# try:
#    import dolfinx
# except ImportError:
#    !conda install -c conda-forge fenics-dolfinx=0.10.0 mpich pyvista meshio

# Installation via script https://fem-on-colab.github.io/packages.html
import dolfinx
import numpy as np
from dolfinx import mesh, fem, io, log
from dolfinx.mesh import create_unit_square, locate_entities, meshtags
import ufl
from mpi4py import MPI
from petsc4py import PETSc
from petsc4py.PETSc import ScalarType

from dolfinx.fem.petsc import NonlinearProblem

from numpy.matrixlib import defmatrix
from ufl.algorithms.formfiles import load_forms

from dolfinx.nls.petsc import NewtonSolver

# from dolfinx.io import gmshio
import meshio

t = 0.0  # Start time
T = 3.0  # End time
num_steps = 50  # Number of time steps
dt = (T - t) / num_steps  # Time step size
# load_amp = 0.0035      # 5 cm specimen
load_amp = 0.01  # 10 cm specimen
length = 10.0

# from google.colab import drive
# drive.mount(/content/drive/maillage/nom.msh)

##########################################
################ Geometry ################
##########################################
import os


def create_mesh(mesh, cell_type, prune_z=True):
    """returns meshio mesh including physucal markers for ther given type
    prune_z argument is when we want to use 2d meshes"""
    cells = mesh.get_cells_type(cell_type)
    # cell_data = mesh.get_cell_data("gmsh:physical", cell_type)
    points = mesh.points[:, :2] if prune_z else mesh.points
    out_mesh = meshio.Mesh(points=points, cells={cell_type: cells})
    # out_mesh = meshio.Mesh(points=points, cells={cell_type: cells}, cell_data={"name_to_read":[cell_data]})
    return out_mesh


proc = MPI.COMM_WORLD.rank
if proc == 0:

    # cmd = 'curl -o ./Dogbone.msh https://zenodo.org/record/7735823/files/Dogbone.msh?download=1' # coarse mesh
    # os.system(cmd)

    # Read in mesh
    # msh = meshio.read("Dogbone_refined.msh")
    msh = meshio.read("Flat_specimen_refined.msh")
    # Create and save one file for the mesh, and one file for the facets
    triangle_mesh = create_mesh(msh, "tetra", prune_z=False)
    line_mesh = create_mesh(msh, "line", prune_z=True)
    meshio.write("mesh.xdmf", triangle_mesh)
    meshio.write("mt.xdmf", line_mesh)

with io.XDMFFile(MPI.COMM_WORLD, "mesh.xdmf", "r") as xdmf:
    domain = xdmf.read_mesh(name="Grid")
    # ct = xdmf.read_meshtags(domain, name="Grid")
    pass

domain.topology.create_connectivity(domain.topology.dim, domain.topology.dim - 1)

import os

cmd = "rm -r results_plasticity"
os.system(cmd)
fic = io.XDMFFile(domain.comm, "results_plasticity/res.xdmf", "w")
fic.write_mesh(domain)

##########################################
################ Space ################
##########################################

print("shape", domain.topology.dim)
# V = fem.VectorFunctionSpace(domain, ("CG", 1))
# W = fem.FunctionSpace(domain, ('DG', 0))
# WT = fem.TensorFunctionSpace(domain, ('DG', 0))
V = fem.functionspace(domain, ("CG", 1, (domain.topology.dim,)))
W = fem.functionspace(domain, ("DG", 0))
WT = fem.functionspace(domain, ("DG", 0, (domain.topology.dim, domain.topology.dim)))
x = ufl.SpatialCoordinate(domain)


def project(v, target_func, bcs=[]):
    # Ensure we have a mesh and attach to measure
    V = target_func.function_space
    metadata = {"quadrature_degree": 2}
    # metadata = {"quadrature_degree": 4}
    # dx = ufl.Measure("dx", domain=domain, metadata=metadata)
    dx = ufl.Measure("dx", domain=domain, metadata=metadata)
    # Define variational problem for projection
    w = ufl.TestFunction(V)
    Pv = ufl.TrialFunction(V)
    a = fem.form(ufl.inner(Pv, w) * dx)
    L = fem.form(ufl.inner(v, w) * dx)
    # Assemble linear system
    A = fem.petsc.assemble_matrix(a, bcs)
    A.assemble()
    b = fem.petsc.assemble_vector(L)
    fem.petsc.apply_lifting(b, [a], [bcs])
    b.ghostUpdate(addv=PETSc.InsertMode.ADD, mode=PETSc.ScatterMode.REVERSE)
    fem.petsc.set_bc(b, bcs)

    # Solve linear system
    solver = PETSc.KSP().create(A.getComm())
    solver.setOperators(A)
    solver.solve(b, target_func.vector)
    return target_func


t_paraview = 0


##########################################
################ Dirichlet BC ################
##########################################

def dirichlet_bcs(domain, space, disp_value):
    boundary_left = lambda x: x[0] <= (-length + 1e-8)
    boundary_right = lambda x: x[0] >= (+length - 1e-8)
    facet_dim = domain.topology.dim - 1
    boundary_left_facets = mesh.locate_entities_boundary(
        domain, facet_dim, boundary_left
    )
    boundary_right_facets = mesh.locate_entities_boundary(
        domain, facet_dim, boundary_right
    )
    u_left = fem.Constant(domain, -disp_value)
    u_right = fem.Constant(domain, disp_value)
    boundary_left_dofs = fem.locate_dofs_topological(
        space, facet_dim, boundary_left_facets
    )
    boundary_right_dofs = fem.locate_dofs_topological(
        space, facet_dim, boundary_right_facets
    )
    bc_left = fem.dirichletbc(u_left, boundary_left_dofs, space)
    bc_right = fem.dirichletbc(u_right, boundary_right_dofs, space)
    bcs = [bc_left, bc_right]
    return bcs


# right boudnary to integrate force
boundary_right = lambda x: x[0] >= (+length - 1e-8)
facets = locate_entities(domain, domain.topology.dim - 1, boundary_right)
facet_markers = np.full_like(facets, 1)
facet_tag = meshtags(domain, domain.topology.dim - 1, facets, facet_markers)
ds = ufl.Measure("ds", domain=domain, subdomain_data=facet_tag)

# disp_value_0 = np.array((0,) * domain.geometry.dim, dtype=PETSc.ScalarType)
# bcs = dirichlet_bcs(domain, V, disp_value = disp_value_0)

# mecanique
E = 200000
ν = 0.3
mu_lame = E / (2.0 * (1.0 + ν))
lambda_lame = E * ν / ((1.0 + ν) * (1.0 - 2.0 * ν))
# sigma_Y = 100
sigma_Y = 100
Q_var = 50  # *10
k = 1000  # *10

# pert = fem.Function(W)
# pert.interpolate(lambda x:0.1*np.sin(x[0]) )

# definition of a random field for use as perturbation in plastic update
quant_param = fem.Function(W)
quant_param.interpolate(
    lambda x: 1.5e-1
    * (1.0e-10 * np.sin((x[0] + x[1]) / 0.25) + 1.0)
    * sigma_Y
    / mu_lame
)
# print(rand_f.x.array)
# rand_f.x.array[:] = np.random.randn(len(rand_f.x.array))
# print(rand_f.x.array)
quant_param.name = "quant_param"
fic.write_function(quant_param)


def sigma_hooke(eps):
    """Return an expression for the stress σ given a displacement field"""
    return lambda_lame * ufl.tr(eps) * ufl.Identity(tdim) + 2.0 * mu_lame * eps


def epsilon(v):
    """Return an expression for the stress σ given a displacement field"""
    return 0.5 * (ufl.grad(v) + ufl.grad(v).T)


def sigma_d(sigma):
    """Return an expression of stress's deviatoric stress"""
    return sigma - (1.0 / 3.0) * ufl.tr(sigma) * ufl.Identity(tdim)


def J(sigma):
    """Return ..."""
    # res = ufl.sqrt((3./2.)*ufl.inner(sigma_d(sigma), sigma_d(sigma)))
    return ufl.sqrt((3.0 / 2.0) * ufl.inner(sigma_d(sigma), sigma_d(sigma)))


zero = fem.Constant(domain, 0.0)


def func(sigma, p):
    R_p = Q_var * (1 - ufl.exp(-k * p))
    return J(sigma) - sigma_Y - R_p


def normal(sigma):
    return (3.0 / (2.0 * J(sigma))) * sigma_d(sigma)


def update_intern_var(Param, eps):

    sigma_star = sigma_hooke(eps - Param.eps_p_old)

    f_func = func(sigma_star, Param.p_old)
    n = normal(sigma_star)

    R_prime = Q_var * (k * ufl.exp(-k * Param.p_old))
    f_prime = -R_prime - 3 * mu_lame
    # delta_p = - (1./f_prime) * ( func(sigma_star, Param.p_old) + 25. + ufl.exp(rand_f) )

    delta_p = -(1.0 / f_prime) * func(sigma_star, Param.p_old)
    if 0:  # quantised plasticity
        delta_p_0 = delta_p
        delta_p_min = quant_param
        # delta_p = - (1./f_prime) * ( func(sigma_star, Param.p_old) + 25. + 10.*ufl.sin( (x[0]+x[1])/3. ) + ufl.exp(rand_f) )
        # delta_p = delta_p_0 + delta_p_more

        # delta_p_min = 0.1 * ( 1. + 0.5*ufl.sin( (x[0]+x[1])/3. ) ) * sigma_Y / mu_lame
        # delta_p = ufl.Max( delta_p_0 , delta_p_0 )
        delta_p = ufl.conditional(ufl.ge(delta_p_0, delta_p_min), delta_p_0, 0.0)

    # p = Param.p_old + delta_p
    # eps_p = Param.eps_p_old + delta_p * n
    # eps_p = ufl.conditional( ufl.ge(f_func, 0.), eps_p, Param.eps_p_old )
    if 0:
        delta_p = ufl.conditional(ufl.ge(f_func, 0.0), delta_p, zero)
        delta_eps_p = delta_p * n
    elif 1 or t_paraview == 0:
        delta_eps_p = ufl.conditional(ufl.ge(f_func, 0.0), delta_p * n, 0.0 * n)
        # eps_p = Param.eps_p_old + delta_eps_p
    else:
        # eps_p = Param.eps_p_old + delta_p*n
        delta_eps_p = delta_p * n
    # delta_p = Param.p_old + ufl.sqrt( 2./3. * ufl.inner(eps_p-Param.eps_p_old,eps_p-Param.eps_p_old) )
    delta_p = ufl.sqrt(2.0 / 3.0 * ufl.inner(delta_eps_p, delta_eps_p))

    return delta_p, delta_eps_p


def sigma(Param, u):
    # _ , eps_p = compute_epsilon_p( Param, epsilon(u) )
    _, delta_eps_p = update_intern_var(Param, epsilon(u))
    return sigma_hooke(epsilon(u) - (Param.eps_p_old + delta_eps_p))


# def p_incr_fun( Param, eps_p ):
# return ufl.sqrt( 2./3. * ufl.inner( eps_p - Param.eps_p_old , eps_p - Param.eps_p_old ) )
#    return eps_p[0,0] - Param.eps_p_old[0,0]

# def p_tot_fun( Param, eps_p ):
#    #return ufl.sqrt( 2./3. * ufl.inner( eps_p , eps_p ) )
#    return eps_p[0,0]

# Define solution variable, and interpolate initial solution for visualization in Paraview
tdim = domain.topology.dim
fdim = tdim - 1


# interns var:
class intern_var:
    def __init__(self, p_init, eps_p_init):
        self.p_old = p_init
        self.eps_p_old = eps_p_init


# p = fem.Function(W)
p_old = fem.Function(W)
# eps_p = fem.Function(WT)
eps_p_old = fem.Function(WT)
# p.x.array[:] = 0.*p.x.array
# p_old.x.array[:] = 0.*p_old.x.array
# eps_p.x.array[:] = 0.*eps_p.x.array
# eps_p_old.x.array[:] = 0.*eps_p_old.x.array
Param = intern_var(p_old, eps_p_old)

metadata = {"quadrature_degree": 1}
dx = ufl.Measure("dx", domain=domain, metadata=metadata)

v = ufl.TestFunction(V)
du = ufl.TrialFunction(V)

uh = fem.Function(V)
# ds = ufl.Measure('ds', domain=domain, subdomain_data=facet_tag, metadata=metadata)
F = ufl.inner(sigma(Param, uh), ufl.sym(ufl.grad(v))) * dx
# F -= ufl.inner( g , v) * dx
# F = ufl.inner(sigma(Param,uh), ufl.sym(ufl.grad(v))) * dx

# Create the Jacobian matrix, dF/du
Jacobian_form = ufl.derivative(F, uh, du)

disp_value = np.array(
    (
        load_amp,
        0.1 * load_amp,
        0,
    ),
    dtype=PETSc.ScalarType,
)
bcs = dirichlet_bcs(domain, V, disp_value=disp_value)

# problem = fem.petsc.NonlinearProblem(F, uh, bcs, Jacobian_form)

from dolfinx.fem.petsc import NewtonSolverNonlinearProblem
from dolfinx.nls.petsc import NewtonSolver

problem = NewtonSolverNonlinearProblem(F, uh, bcs=bcs, J=Jacobian_form)
solver = NewtonSolver(domain.comm, problem)

solver.atol = 1e-8
solver.rtol = 1e-8
solver.max_it = 50
solver.convergence_criterion = "incremental"

print("______________________________")
print("______________________________")
print("______________________________")


# dt = dt*0.5
force_vec = []
for i in range(num_steps + 1):  # (num_steps+1):
    print("_____________i=____________", i)
    t += dt
    bcs = dirichlet_bcs(domain, V, disp_value * t)
    problem.bcs = bcs
    print("disp_value*t", disp_value * t)
    log.set_log_level(log.LogLevel.INFO)
    num_its, converged = solver.solve(uh)
    log.set_log_level(log.LogLevel.WARNING)
    uh.name = "displacement"
    fic.write_function(uh, t_paraview)

    # Epsilon:
    eps = epsilon(uh)
    # p, eps_p = compute_epsilon_p(Param, eps)
    delta_p, delta_eps_p = update_intern_var(Param, eps)

    epsilon_proj = fem.Function(WT)
    # epsilon_proj = project(eps,epsilon_proj)
    epsilon_proj.interpolate(fem.Expression(eps, WT.element.interpolation_points))
    epsilon_proj.name = "Epsilon"
    fic.write_function(epsilon_proj, t_paraview)

    # Epsilon_p:
    epsilon_p_proj = fem.Function(WT)
    # epsilon_p_proj = project(eps_p,epsilon_p_proj)
    epsilon_p_proj.interpolate(
        fem.Expression(delta_eps_p + Param.eps_p_old, WT.element.interpolation_points)
    )
    epsilon_p_proj.name = "Epsilon_p"
    fic.write_function(epsilon_p_proj, t_paraview)

    # Cumulative plastic strain
    p_proj = fem.Function(W)
    # p_proj = project(p,p_proj)
    # p_proj = fem.Expression( p , W.element.interpolation_points )
    p_proj.interpolate(
        fem.Expression(delta_p + Param.p_old, W.element.interpolation_points)
    )
    p_proj.name = "Cumulative plastic strain"
    fic.write_function(p_proj, t_paraview)

    # Von Mises stress:
    stress = sigma_hooke(eps - (delta_eps_p + Param.eps_p_old))
    von_Mises = J(stress)
    von_Mises_proj = fem.Function(W)
    # von_Mises_proj = project(von_Mises,von_Mises_proj)
    von_Mises_proj.interpolate(
        fem.Expression(von_Mises, W.element.interpolation_points)
    )
    von_Mises_proj.name = "Von Mises stress"
    fic.write_function(von_Mises_proj, t_paraview)

    # https://jsdokken.com/dolfinx-tutorial/chapter3/robin_neumann_dirichlet.html
    stress = sigma_hooke(eps - (delta_eps_p + Param.eps_p_old))
    force = fem.form(stress[0, 0] * ds(1))
    force = fem.assemble_scalar(force)
    force_vec.append(force)
    print("Reaction force", force)

    # Increments of cumulative plastic strain to debug
    if 1:
        p_incr = delta_eps_p[0, 0] - delta_p
        # p_incr = ( eps_p[0,0] - Param.eps_p_old[0,0] ) - ( p - Param.p_old )
        # p_incr = p_incr_fun( Param , eps_p )
        p_incr_proj = fem.Function(W)
        # p_incr_proj = project(p_incr,p_incr_proj)
        p_incr_proj.interpolate(fem.Expression(p_incr, W.element.interpolation_points))
        p_incr_proj.name = "Cumulative plastic increment error"
        fic.write_function(p_incr_proj, t_paraview)

    # cumulative plastic strain to debug
    if 1:
        p_tot = (Param.eps_p_old[0, 0] + delta_eps_p[0, 0]) - (Param.p_old + delta_p)
        # p_tot = eps_p[0,0] - p
        # p_incr = p_incr_fun( Param , eps_p )
        p_tot_proj = fem.Function(W)
        # p_tot_proj = project(p_tot,p_tot_proj)
        p_tot_proj.interpolate(fem.Expression(p_tot, W.element.interpolation_points))
        p_tot_proj.name = "Cumulated plastic error"
        fic.write_function(p_tot_proj, t_paraview)

    # delta_eps_p = eps_p - Param.eps_p_old
    delta_eps_p_proj = fem.Function(WT)
    delta_eps_p_proj.interpolate(
        fem.Expression(delta_eps_p, WT.element.interpolation_points)
    )
    delta_eps_p_proj.name = "delta Eps_p"

    Param.p_old.interpolate(
        fem.Expression(Param.p_old + delta_p, W.element.interpolation_points)
    )
    # Param.p_old = project(p,Param.p_old)
    if 0:
        Param.eps_p_old.interpolate(
            fem.Expression(eps_p, WT.element.interpolation_points)
        )
        # Param.eps_p_old = project(eps_p,Param.eps_p_old)
    else:
        Param.eps_p_old.x.array[:] = (
            delta_eps_p_proj.x.array[:] + Param.eps_p_old.x.array[:]
        )

    t_paraview += 1
    print("t_paraview = ", t_paraview)
    # Scatter forward the solution vector to update ghost values (https://docs.fenicsproject.org/dolfinx/main/python/demos/demo_elasticity.html)

print(" c'est fini !!!!!!!!!!!!!")
fic.close()

print("reaction forces", force_vec)
import matplotlib.pyplot as plt

plt.plot(force_vec)
plt.grid()
plt.show()

"""# Nouvelle section"""
